; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=instcombine < %s | FileCheck %s

; Test that sqrt library calls are converted to llvm.sqrt intrinsic when the
; argument is known to be non-negative (cannot set errno).

declare double @sqrt(double)
declare float @sqrtf(float)
declare double @llvm.fabs.f64(double)
declare float @llvm.fabs.f32(float)

; sqrt(x * x) - argument is a square, always non-negative
define double @sqrt_square(double %x) {
; CHECK-LABEL: @sqrt_square(
; CHECK-NEXT:    [[SQ:%.*]] = fmul double [[X:%.*]], [[X]]
; CHECK-NEXT:    [[SQRT:%.*]] = call double @llvm.sqrt.f64(double [[SQ]])
; CHECK-NEXT:    ret double [[SQRT]]
;
  %sq = fmul double %x, %x
  %sqrt = call double @sqrt(double %sq)
  ret double %sqrt
}

; sqrt(fabs(x)) - argument is always non-negative
define double @sqrt_fabs(double %x) {
; CHECK-LABEL: @sqrt_fabs(
; CHECK-NEXT:    [[A:%.*]] = call double @llvm.fabs.f64(double [[X:%.*]])
; CHECK-NEXT:    [[SQRT:%.*]] = call double @llvm.sqrt.f64(double [[A]])
; CHECK-NEXT:    ret double [[SQRT]]
;
  %a = call double @llvm.fabs.f64(double %x)
  %sqrt = call double @sqrt(double %a)
  ret double %sqrt
}

; sqrt(a*a + b*b) - sum of squares, always non-negative
define double @sqrt_sum_of_squares(double %a, double %b) {
; CHECK-LABEL: @sqrt_sum_of_squares(
; CHECK-NEXT:    [[A2:%.*]] = fmul double [[A:%.*]], [[A]]
; CHECK-NEXT:    [[B2:%.*]] = fmul double [[B:%.*]], [[B]]
; CHECK-NEXT:    [[SUM:%.*]] = fadd double [[A2]], [[B2]]
; CHECK-NEXT:    [[SQRT:%.*]] = call double @llvm.sqrt.f64(double [[SUM]])
; CHECK-NEXT:    ret double [[SQRT]]
;
  %a2 = fmul double %a, %a
  %b2 = fmul double %b, %b
  %sum = fadd double %a2, %b2
  %sqrt = call double @sqrt(double %sum)
  ret double %sqrt
}

; sqrtf version - sqrt(x * x)
define float @sqrtf_square(float %x) {
; CHECK-LABEL: @sqrtf_square(
; CHECK-NEXT:    [[SQ:%.*]] = fmul float [[X:%.*]], [[X]]
; CHECK-NEXT:    [[SQRT:%.*]] = call float @llvm.sqrt.f32(float [[SQ]])
; CHECK-NEXT:    ret float [[SQRT]]
;
  %sq = fmul float %x, %x
  %sqrt = call float @sqrtf(float %sq)
  ret float %sqrt
}

; uitofp produces non-negative value
define double @sqrt_uitofp(i32 %x) {
; CHECK-LABEL: @sqrt_uitofp(
; CHECK-NEXT:    [[F:%.*]] = uitofp i32 [[X:%.*]] to double
; CHECK-NEXT:    [[SQRT:%.*]] = call double @llvm.sqrt.f64(double [[F]])
; CHECK-NEXT:    ret double [[SQRT]]
;
  %f = uitofp i32 %x to double
  %sqrt = call double @sqrt(double %f)
  ret double %sqrt
}

; Negative test: unknown argument, cannot optimize
define double @sqrt_unknown(double %x) {
; CHECK-LABEL: @sqrt_unknown(
; CHECK-NEXT:    [[SQRT:%.*]] = call double @sqrt(double [[X:%.*]])
; CHECK-NEXT:    ret double [[SQRT]]
;
  %sqrt = call double @sqrt(double %x)
  ret double %sqrt
}

; Negative test: sitofp can be negative
define double @sqrt_sitofp(i32 %x) {
; CHECK-LABEL: @sqrt_sitofp(
; CHECK-NEXT:    [[F:%.*]] = sitofp i32 [[X:%.*]] to double
; CHECK-NEXT:    [[SQRT:%.*]] = call double @sqrt(double [[F]])
; CHECK-NEXT:    ret double [[SQRT]]
;
  %f = sitofp i32 %x to double
  %sqrt = call double @sqrt(double %f)
  ret double %sqrt
}

; Already an intrinsic - no change needed
define double @sqrt_intrinsic_square(double %x) {
; CHECK-LABEL: @sqrt_intrinsic_square(
; CHECK-NEXT:    [[SQ:%.*]] = fmul double [[X:%.*]], [[X]]
; CHECK-NEXT:    [[SQRT:%.*]] = call double @llvm.sqrt.f64(double [[SQ]])
; CHECK-NEXT:    ret double [[SQRT]]
;
  %sq = fmul double %x, %x
  %sqrt = call double @llvm.sqrt.f64(double %sq)
  ret double %sqrt
}

declare double @llvm.sqrt.f64(double)
